Version: 1.20.9
Installer:
- Architecture: x86
  InstallerUrl: https://github.com/yourtablecloth/TableCloth/releases/download/v1.20.9/SporkBootstrap_1.20.9.0_Release_arm64.exe
Locale: []
ReleaseTime: 2026-07-27T14:21:22.0000000Z
